<style type="text/css">
	p.head {font-size:1.2em; margin: 2em 0}
	p.head strong {font-size:2em;}
	p.head em {font-style:normal;font-weight:bold; font-size:1.6em;}
	p.normalized em {font-style:normal;font-weight:bold; font-size:1.2em;}
	p.normalized strong {font-size:1.6em;}
</style>


<p class="head"><strong tal:content="word | wordh" /> is <em tal:content="spam"/> spam vs
<em tal:content="ham"/> ham.</p>


<p class="normalized">normalized <em tal:content="normspam"/> spam vs <em tal:content="normham"/> ham. <strong>${spammy}% spammy</strong></p>

